package etcodehome.freeterraforged.server.command;

import java.util.List;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import org.jetbrains.annotations.Nullable;

import com.mojang.brigadier.Command;
import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import com.mojang.brigadier.exceptions.DynamicCommandExceptionType;
import com.mojang.brigadier.exceptions.SimpleCommandExceptionType;

import etcodehome.freeterraforged.FTFCommon;
import etcodehome.freeterraforged.world.worldgen.FTFRandomState;
import etcodehome.freeterraforged.world.worldgen.GeneratorContext;
import etcodehome.freeterraforged.world.worldgen.cell.Cell;
import etcodehome.freeterraforged.world.worldgen.cell.heightmap.WorldLookup;
import etcodehome.freeterraforged.world.worldgen.cell.terrain.Terrain;
import etcodehome.freeterraforged.world.worldgen.cell.terrain.TerrainType;
import net.minecraft.ChatFormatting;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.commands.SharedSuggestionProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.ClickEvent;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.ComponentUtils;
import net.minecraft.network.chat.HoverEvent;
import net.minecraft.server.MinecraftServer;

/**
 * {@code /ftf locate terrain <terrain> [radius]} finds the nearest point of an FTF terrain type.
 *
 * <p>The world's terrain is sampled on a grid by a small pool of worker threads and the answer is reported back on the
 * server thread, so the server keeps ticking while the search runs. Sampling goes through {@link WorldLookup#applyCell}
 * without loading, so it reuses terrain tiles that already exist but never creates or waits on new ones.
 */
public final class LocateTerrainCommand {
	static final int DEFAULT_RADIUS = 10_000;
	static final int MAX_RADIUS = 100_000;
	/** Grid spacing in blocks. Thin terrain (rivers, beaches, volcano pipes) is sampled twice as densely. */
	private static final int STEP = 32;
	private static final int FINE_STEP = 16;
	private static final long TIMEOUT_SECONDS = 60L;
	private static final int WORKERS = Math.max(1, Runtime.getRuntime().availableProcessors() / 2);
	private static final ThreadPoolExecutor EXECUTOR = createExecutor();
	private static final Cell BLANK_CELL = new Cell();

	/** Every terrain a lookup can report. Island beaches are reported as beaches, so they are left out. */
	private static final List<Terrain> TERRAINS = List.of(
		TerrainType.DEEP_OCEAN,
		TerrainType.SHALLOW_OCEAN,
		TerrainType.COAST,
		TerrainType.BEACH,
		TerrainType.RIVER,
		TerrainType.WETLAND,
		TerrainType.FLATS,
		TerrainType.BADLANDS,
		TerrainType.PLATEAU,
		TerrainType.HILLS,
		TerrainType.MOUNTAINS_1,
		TerrainType.MOUNTAINS_2,
		TerrainType.MOUNTAINS_3,
		TerrainType.MOUNTAIN_CHAIN,
		TerrainType.VOLCANO,
		TerrainType.VOLCANO_PIPE,
		TerrainType.ISLAND,
		TerrainType.ISLAND_MOUNTAINS,
		TerrainType.MUSHROOM_FIELDS
	);

	private static final String KEY = FTFCommon.MOD_ID + ".commands.locate.terrain.";
	private static final DynamicCommandExceptionType ERROR_UNKNOWN_TERRAIN = new DynamicCommandExceptionType(
		name -> Component.translatableWithFallback(KEY + "unknown", "Unknown terrain type: %s", name)
	);
	private static final SimpleCommandExceptionType ERROR_NOT_FTF = new SimpleCommandExceptionType(
		Component.translatableWithFallback(KEY + "not_ftf", "This dimension is not generated by FreeTerraForged")
	);

	private LocateTerrainCommand() {
	}

	public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
		dispatcher.register(Commands.literal("ftf")
			.requires(source -> source.hasPermission(2))
			.then(Commands.literal("locate")
				.requires(source -> source.hasPermission(2))
				.then(Commands.literal("terrain")
					.then(Commands.argument("terrain", StringArgumentType.word())
						.suggests((context, builder) -> SharedSuggestionProvider.suggest(TERRAINS.stream().map(Terrain::getName), builder))
						.executes(context -> locate(context.getSource(), StringArgumentType.getString(context, "terrain"), DEFAULT_RADIUS))
						.then(Commands.argument("radius", IntegerArgumentType.integer(STEP, MAX_RADIUS))
							.executes(context -> locate(
								context.getSource(),
								StringArgumentType.getString(context, "terrain"),
								IntegerArgumentType.getInteger(context, "radius")
							))
						)
					)
				)
			)
		);
	}

	private static int locate(CommandSourceStack source, String name, int radius) throws CommandSyntaxException {
		Terrain target = TerrainType.get(name);
		if (target == null || !TERRAINS.contains(target)) {
			throw ERROR_UNKNOWN_TERRAIN.create(name);
		}
		GeneratorContext context = (Object) source.getLevel().getChunkSource().randomState() instanceof FTFRandomState state
			? state.generatorContext()
			: null;
		if (context == null) {
			throw ERROR_NOT_FTF.create();
		}

		WorldLookup lookup = context.lookup;
		BlockPos origin = BlockPos.containing(source.getPosition());
		MinecraftServer server = source.getServer();
		int step = isThin(target) ? FINE_STEP : STEP;
		long start = System.nanoTime();
		source.sendSuccess(() -> Component.translatableWithFallback(KEY + "searching", "Searching for %s within %s blocks...", target.getName(), radius), false);
		ParallelGridSearch.findNearest(
			origin.getX(),
			origin.getZ(),
			step,
			radius,
			() -> terrainTest(lookup, target),
			EXECUTOR,
			WORKERS,
			start + TimeUnit.SECONDS.toNanos(TIMEOUT_SECONDS)
		).whenComplete((result, error) -> {
			long elapsedNanos = System.nanoTime() - start;
			server.execute(() -> report(source, target, result, error, elapsedNanos));
		});
		return Command.SINGLE_SUCCESS;
	}

	private static ParallelGridSearch.PointTest terrainTest(WorldLookup lookup, Terrain target) {
		Cell cell = new Cell();
		return (x, z) -> {
			// Heightmap passes accumulate into some fields (e.g. riverMask), so start every sample from a blank cell.
			cell.copyFrom(BLANK_CELL);
			lookup.applyCell(cell, x, z, false);
			return cell.terrain == target;
		};
	}

	private static boolean isThin(Terrain terrain) {
		return terrain == TerrainType.RIVER || terrain == TerrainType.BEACH || terrain == TerrainType.VOLCANO_PIPE;
	}

	private static void report(CommandSourceStack source, Terrain target, @Nullable ParallelGridSearch.Result result, @Nullable Throwable error, long elapsedNanos) {
		String name = target.getName();
		if (result == null) {
			FTFCommon.LOGGER.error("Locating terrain {} failed", name, error);
			source.sendFailure(Component.translatableWithFallback(KEY + "failed", "Searching for %s failed; see the server log for details", name));
			return;
		}
		FTFCommon.LOGGER.info("Locating terrain {} took {} ms ({} samples on {} threads)", name, TimeUnit.NANOSECONDS.toMillis(elapsedNanos), result.samples(), WORKERS);

		ParallelGridSearch.Match match = result.match();
		if (match == null) {
			source.sendFailure(result.timedOut()
				? Component.translatableWithFallback(KEY + "timed_out", "Could not find %s within %s blocks before the search timed out", name, result.searchedRadius())
				: Component.translatableWithFallback(KEY + "not_found", "Could not find %s within %s blocks", name, result.searchedRadius()));
			return;
		}
		int distance = (int) Math.sqrt((double) match.distanceSq());
		Component coordinates = ComponentUtils.wrapInSquareBrackets(Component.translatable("chat.coordinates", match.x(), "~", match.z()))
			.withStyle(style -> style
				.withColor(ChatFormatting.GREEN)
				.withClickEvent(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, "/tp @s " + match.x() + " ~ " + match.z()))
				.withHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, Component.translatable("chat.coordinates.tooltip"))));
		source.sendSuccess(() -> Component.translatableWithFallback(KEY + "success", "The nearest %s is at %s (%s blocks away)", name, coordinates, distance), false);
		if (result.timedOut()) {
			source.sendSuccess(() -> Component.translatableWithFallback(KEY + "inexact", "The search timed out, so a closer %s may exist", name), false);
		}
	}

	private static ThreadPoolExecutor createExecutor() {
		AtomicInteger threads = new AtomicInteger();
		ThreadPoolExecutor executor = new ThreadPoolExecutor(WORKERS, WORKERS, 30L, TimeUnit.SECONDS, new LinkedBlockingQueue<>(), task -> {
			Thread thread = new Thread(task, "FTF-Locate-" + threads.incrementAndGet());
			thread.setDaemon(true);
			return thread;
		});
		executor.allowCoreThreadTimeOut(true);
		return executor;
	}
}
